insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('연탄가스 연기 너무 맵다 ㅠㅠㅠㅠ', '알바하지마', '익명의 알바생', 'd', 1, 1, 1, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('고기 나르기 힘들다;', '알바하지마', '익명의 알바생', 'a', 1, 1, 1, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('편의점 알바하다가 사망하겠다;', '알바하지마', '익명의 알바생', 'w', 2, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('편의점 점장 맘에 안든다 하지마라;', '알바하지마', '익명의 알바생', 'w', 2, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('놀이동산 알바 한여름에 하니 뒤지겠다;', '알바하지마', '익명의 알바생', 'w', 3, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('워터파크 알바 개꿀^^', '알바하지마', '익명의 알바생', 'w', 3, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('외주 받아요 돈만 준다면요', '알바하지마', '익명의 알바생', 'w', 4, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('js극혐;', '알바하지마', '익명의 알바생', 'w', 4, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('청소해드립니다. 너무 더러운 곳 말고는요 ㅎㅎ', '알바하지마', '익명의 알바생', 'w', 5, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('느그들 변기 평소에 잘 청소해라', '알바하지마', '익명의 알바생', 'w', 5, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('상하차하다가 뒤지겠다;', '알바하지마', '익명의 알바생', 'w', 6, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('니네 돈 많이 준다고 이거 하지마라', '알바하지마', '익명의 알바생', 'w', 6, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('허구한 날 자판만 치니 인생 노잼이다', '알바하지마', '익명의 알바생', 'w', 7, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('회계 갸꿀~~', '알바하지마', '익명의 알바생', 'w', 7, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('진짜 니넨 꿀알바를 못찾냐', '알바하지마', '익명의 알바생', 'w', 8, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('꿀알바 찾는 팁 알려준다', '알바하지마', '익명의 알바생', 'w', 8, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('고기고기고기 냄새 오진다', '알바하지마', '익명의 알바생', 'w', 1, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('편의점에 변태같은 것들 너무 많이 온다.', '알바하지마', '익명의 알바생', 'w', 2, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('편의점 삼각김밥 개맛있다.', '알바하지마', '익명의 알바생', 'w', 2, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('점심 제공 좀 똑바로 해주세요', '알바하지마', '익명의 알바생', 'w', 2, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('새벽 편돌이 개헬이다', '알바하지마', '익명의 알바생', 'w', 2, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('급식들 왤케 지저분하냐', '알바하지마', '익명의 알바생', 'w', 2, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('내가 하다하다 편돌이까지하네', '알바하지마', '익명의 알바생', 'w', 2, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('편의점 노잼', '알바하지마', '익명의 알바생', 'w', 2, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('편의점 전기 충전 개꿀이다', '알바하지마', '익명의 알바생', 'w', 2, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('교통카드 몰래 충전하다 들킨.ssul', '알바하지마', '익명의 알바생', 'w', 2, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('개꿀잼 알바다', '알바하지마', '익명의 알바생', 'w', 2, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('편의점 호불호 오진다', '알바하지마', '익명의 알바생', 'w', 2, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('잘 생각해보고 해라', '알바하지마', '익명의 알바생', 'w', 2, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('우리 다음 타임 교대 알바 이쁘다', '알바하지마', '익명의 알바생', 'w', 2, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('편의점 황금레시피 알려준다', '알바하지마', '익명의 알바생', 'w', 2, 2, 3, 0, now())
insert into posts (title, content, author, pwd, cat_id, favor, hate, visit, created_date) values ('편의점 삼각김밥 몰래먹다 걸린.ssul', '알바하지마', '익명의 알바생', 'w', 2, 2, 3, 0, now())
insert into comments (content, author, pwd, favor, hate, post_id, created_date) values ('겁나 가엽다...', '익명의 아싸', 'c', 10, 1, 1, now())
insert into comments (content, author, pwd, favor, hate, post_id, created_date) values ('인생 왜그렇게 사냐;', '익명의 아싸', 'a', 1, 10, 1, now())